So sollte es funktionieren
eisenils/schweinberg-leuchtet pull request #1
Opened 2020-04-23 20:18 UTC by felixkeller98

Ist keine elegante Lösung mit der Media Query aber ich seh sonst keinen Weg das Video einmal Horizontal und dann Vertikal zu skalieren :/

2020-04-23 20:20 UTC, felixkeller98 commented
Voll cool das Zeit ein Preview-Build von dem Pull Request macht :)

2020-04-23 20:26 UTC, felixkeller98 commented
Mir ist gerade aufgefallen das ich das zu viel einkommentiert habe.

2020-04-24 04:34 UTC, eisenils commented
Ja richtig cool, dass es da eine Vorschau gibt 👍

2020-04-24 04:40 UTC, eisenils requested changes
Allerdings ist es jetzt durch den Media Query so, dass auf FullScreen nur noch das Video angezeigt wird und nicht mehr der Footer. Das '<FullHeight>'-Element, war da eigentlich schon ganz gut. Vielleicht ja aber auch schon `object-fit: cover;`. Ich versuch es mal 🤔

2020-04-24 06:29 UTC, felixkeller98 commented
> 
> 
> Allerdings ist es jetzt durch den Media Query so, dass auf FullScreen nur noch das Video angezeigt wird und nicht mehr der Footer. Das ''-Element, war da eigentlich schon ganz gut. Vielleicht ja aber auch schon `object-fit: cover;`. Ich versuch es mal 🤔

Was für ein Element meinst du? hab den Footer gar nicht bemerkt

2020-04-25 16:24 UTC, eisenils commented
Das `FullHeight`-Element, das hat tatsächlich immer nur die Device Höhe (100%) genommen

2020-04-25 16:31 UTC, felixkeller98 commented
Das macht es jetzt auch, nur ist momentan die 100vh auf einem div, und um
dieses Div herum und darunter sind ja noch mehr container/elemente deswegen
ist es größer

(Diese Antwort ist in Gmail geschrieben lol)





Am Sa., 25. Apr. 2020 um 18:24 Uhr schrieb Nils <notifications@github.com>:

> Das FullHeight-Element, das hat tatsächlich immer nur die Device Höhe
> (100%) genommen
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eisenils/schweinberg-leuchtet/pull/1#issuecomment-619404646>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPTIH66YNZCSCGWG2IA3J3ROMFEVANCNFSM4MPNAOOA>
> .
>

2020-04-25 18:57 UTC, closed without merging

2020-04-25 18:59 UTC, eisenils commented
Wurde gelöst. Thx 👍

2021-01-22 06:54 UTC, felixkeller98 commented
---------- Forwarded message ---------
Von: Fütterer, Melanie <Melanie.Fuetterer@mosbach.dhbw.de>
Date: Do., 21. Jan. 2021 um 18:09 Uhr
Subject: AW: Webspace zum Hosten des Prototyps - ON18 WD3
To: Felix Keller <felixkeller98@gmail.com>


Hallo Herr Keller,

sie können gerne eine Hosting von mir bekommen. Ich habe ihnen mal einen
Account angelegt - anbei der Zugang:

Verwaltungsoberfläche: login.mittwald.de
Benutzername: p577247
PW: xao_1Hyfzn

Sie erreichen den Account über die Account-URL
http://p577247.mittwaldserver.info

Bei Fragen gerne melden.

Freundliche Grüße
Melanie Fütterer

==============================================
Laborleitung Onlinemedien
Webteam
Stv. Vorsitzende im ÖPR
Email: melanie.fuetterer@mosbach.dhbw.de

Duale Hochschule Baden-Württemberg Mosbach
Oberer Mühlenweg 2-6, 74821 Mosbach
==============================================
------------------------------
*Von:* Felix Keller [felixkeller98@gmail.com]
*Gesendet:* Dienstag, 19. Januar 2021 13:37
*An:* Fütterer, Melanie
*Cc:* nil.eisenhauer.18@lehre.mosbach.dhbw.de; ole.mantei.18; Natascha
Forster
*Betreff:* Webspace zum Hosten des Prototyps - ON18 WD3

Guten Tag Frau Fütterer,

für die Abgabe unseres Semesterprojekts im Modul Web Design 3 benötigt
unsere Gruppe einen freien Webspace zum Hosten des Prototyps/ der Website.
Wir würden hier gerne das Angebot der DHBW in Anspruch nehmen und uns
freuen, wenn Sie uns das entsprechend einrichten können.

Vielen Dank und viele Grüße

Felix Keller